from .constants import PresetEffect, MonoEffect, CustomEffect

MONO_EFFECTS = {
    'Solid (custom color)': MonoEffect.SOLID,
    'Breathing (custom color)': MonoEffect.BREATHING,
    'Meteor (custom color)': MonoEffect.METEOR,
    'Flow (custom color)': MonoEffect.FLOW,
    'Wave (custom color)': MonoEffect.WAVE,
    'Flash (custom color)': MonoEffect.FLASH,
    'Stack (custom color)': MonoEffect.STACK,
    'Catchup (custom color)': MonoEffect.CATCHUP,
}

PRESET_EFFECTS = {
    'Rainbow': PresetEffect.RAINBOW,
    'Colors changing meteors': PresetEffect.COLORS_CHANGING_METEORS,
    'Flowing Colors': PresetEffect.FLOWING_COLORS,
    'Overlaying Flowing': PresetEffect.OVERLAYING_FLOWING,
    'Red stacking': PresetEffect.RED_STACKING,
    'Green stacking': PresetEffect.GREEN_STACKING,
    'Blue stacking': PresetEffect.BLUE_STACKING,
    'Colors changing stacking': PresetEffect.COLORS_CHANGING_STACKING,
    'Fading flowing': PresetEffect.FADING_FLOWING,
    'Color changing cross flowing': PresetEffect.COLOR_CHANGING_CROSS_FLOWING,
    'Cross flowing': PresetEffect.CROSS_FLOWING,
    'Chasing color dots': PresetEffect.CHASING_COLOR_DOTS,
    'Colorful wave': PresetEffect.COLORFUL_WAVE,
    'Burning fire': PresetEffect.BURNING_FIRE,
    'Red meteor': PresetEffect.RED_METEOR,
    'Green meteor': PresetEffect.GREEN_METEOR,
    'Blue meteor': PresetEffect.BLUE_METEOR,
    'Yellow meteor': PresetEffect.YELLOW_METEOR,
    'Cyan meteor': PresetEffect.CYAN_METEOR,
    'Purple meteor': PresetEffect.PURPLE_METEOR,
    'White meteor': PresetEffect.WHITE_METEOR,
    'Red wave': PresetEffect.RED_WAVE,
    'Green wave': PresetEffect.GREEN_WAVE,
    'Blue wave': PresetEffect.BLUE_WAVE,
    'Yellow wave': PresetEffect.YELLOW_WAVE,
    'Cyan wave': PresetEffect.CYAN_WAVE,
    'Purple wave': PresetEffect.PURPLE_WAVE,
    'White wave': PresetEffect.WHITE_WAVE,
    'Red chasing dots': PresetEffect.RED_CHASING_DOTS,
    'Green chasing dots': PresetEffect.GREEN_CHASING_DOTS,
    'Blue chasing dots': PresetEffect.BLUE_CHASING_DOTS,
    'Yellow chasing dots': PresetEffect.YELLOW_CHASING_DOTS,
    'Cyan chasing dots': PresetEffect.CYAN_CHASING_DOTS,
    'White chasing dots': PresetEffect.WHITE_CHASING_DOTS,
    'Purple chasing dots': PresetEffect.PURPLE_CHASING_DOTS,
    'Cyan dots blink on silver': PresetEffect.CYAN_DOTS_BLINK_ON_SILVER,
    'Purple dots blink on silver': PresetEffect.PURPLE_DOTS_BLINK_ON_SILVER,
    'Yellow dots blink on silver': PresetEffect.YELLOW_DOTS_BLINK_ON_SILVER,
    'Blue dots blink on silver': PresetEffect.BLUE_DOTS_BLINK_ON_SILVER,
    'Green dots blink on silver': PresetEffect.GREEN_DOTS_BLINK_ON_SILVER,
    'Red dots blink on silver': PresetEffect.RED_DOTS_BLINK_ON_SILVER,
    'Red and Green flowing': PresetEffect.RED_AND_GREEN_FLOWING,
    'Red and blue flowing': PresetEffect.RED_AND_BLUE_FLOWING,
    'Red and yellow flowing': PresetEffect.RED_AND_YELLOW_FLOWING,
    'Red and cyan flowing': PresetEffect.RED_AND_CYAN_FLOWING,
    'Red and purple flowing': PresetEffect.RED_AND_PURPLE_FLOWING,
    'Red and white flowing': PresetEffect.RED_AND_WHITE_FLOWING,
    'Green and blue flowing': PresetEffect.GREEN_AND_BLUE_FLOWING,
    'Green and yellow flowing': PresetEffect.GREEN_AND_YELLOW_FLOWING,
    'Green and cyan flowing': PresetEffect.GREEN_AND_CYAN_FLOWING,
    'Green and purple flowing': PresetEffect.GREEN_AND_PURPLE_FLOWING,
    'Green and white flowing': PresetEffect.GREEN_AND_WHITE_FLOWING,
    'Blue and yellow flowing': PresetEffect.BLUE_AND_YELLOW_FLOWING,
    'Blue and cyan flowing': PresetEffect.BLUE_AND_CYAN_FLOWING,
    'Blue and purple flowing': PresetEffect.BLUE_AND_PURPLE_FLOWING,
    'Blue and white flowing': PresetEffect.BLUE_AND_WHITE_FLOWING,
    'Yellow and cyan flowing': PresetEffect.YELLOW_AND_CYAN_FLOWING,
    'Yellow and purple flowing': PresetEffect.YELLOW_AND_PURPLE_FLOWING,
    'Yellow and white flowing': PresetEffect.YELLOW_AND_WHITE_FLOWING,
    'Cyan and purple flowing': PresetEffect.CYAN_AND_PURPLE_FLOWING,
    'Cyan and white flowing': PresetEffect.CYAN_AND_WHITE_FLOWING,
    'Red crossing flowing': PresetEffect.RED_CROSSING_FLOWING,
    'Green crossing flowing': PresetEffect.GREEN_CROSSING_FLOWING,
    'Blue crossing flowing': PresetEffect.BLUE_CROSSING_FLOWING,
    'Yellow crossing flowing': PresetEffect.YELLOW_CROSSING_FLOWING,
    'Cyan crossing flowing': PresetEffect.CYAN_CROSSING_FLOWING,
    'Purple crossing flowing': PresetEffect.PURPLE_CROSSING_FLOWING,
    'White crossing flowing': PresetEffect.WHITE_CROSSING_FLOWING,
    'Red arrows': PresetEffect.RED_ARROWS,
    'Green arrows': PresetEffect.GREEN_ARROWS,
    'Blue arrows': PresetEffect.BLUE_ARROWS,
    'Yellow arrows': PresetEffect.YELLOW_ARROWS,
    'Cyan arrows': PresetEffect.CYAN_ARROWS,
    'Purple arrows': PresetEffect.PURPLE_ARROWS,
    'Red cudgel': PresetEffect.RED_CUDGEL,
    'Green cudgel': PresetEffect.GREEN_CUDGEL,
    'Blue cudgel': PresetEffect.BLUE_CUDGEL,
    'Yellow cudgel': PresetEffect.YELLOW_CUDGEL,
    'Cyan cudgel': PresetEffect.CYAN_CUDGEL,
    'Purple cudgel': PresetEffect.PURPLE_CUDGEL,
    'Gaps in cyan': PresetEffect.GAPS_IN_CYAN,
    'Gaps in purple': PresetEffect.GAPS_IN_PURPLE,
    'Gaps in yellow': PresetEffect.GAPS_IN_YELLOW,
    'Gaps in blue': PresetEffect.GAPS_IN_BLUE,
    'Gaps in green': PresetEffect.GAPS_IN_GREEN,
    'Gaps in red': PresetEffect.GAPS_IN_RED,
    'Red breathe': PresetEffect.RED_BREATHE,
    'Green breathe': PresetEffect.GREEN_BREATHE,
    'Blue breathe': PresetEffect.BLUE_BREATHE,
    'Yellow breathe': PresetEffect.YELLOW_BREATHE,
    'Cyan breathe': PresetEffect.CYAN_BREATHE,
    'Purple breathe': PresetEffect.PURPLE_BREATHE,
    'White breathe': PresetEffect.WHITE_BREATHE,
    'Red arrows reverse': PresetEffect.RED_ARROWS_REVERSE,
    'Green arrows reverse': PresetEffect.GREEN_ARROWS_REVERSE,
    'Blue arrows reverse': PresetEffect.BLUE_ARROWS_REVERSE,
    'Yellow arrows reverse': PresetEffect.YELLOW_ARROWS_REVERSE,
    'Cyan arrows reverse': PresetEffect.CYAN_ARROWS_REVERSE,
    'Purple arrows reverse': PresetEffect.PURPLE_ARROWS_REVERSE,
    'Red dots running in cyan': PresetEffect.RED_DOTS_RUNNING_IN_CYAN,
    'Green dots running in purple': PresetEffect.GREEN_DOTS_RUNNING_IN_PURPLE,
    'Blue dots running in yellow': PresetEffect.BLUE_DOTS_RUNNING_IN_YELLOW,
    'Yellow dots running in blue': PresetEffect.YELLOW_DOTS_RUNNING_IN_BLUE,
    'Cyan dots running in green': PresetEffect.CYAN_DOTS_RUNNING_IN_GREEN,
    'Purple dots running in red': PresetEffect.PURPLE_DOTS_RUNNING_IN_RED,
    'White dots running in cyan': PresetEffect.WHITE_DOTS_RUNNING_IN_CYAN,
    'Red fading in and out': PresetEffect.RED_FADING_IN_AND_OUT,
    'Green fading in and out': PresetEffect.GREEN_FADING_IN_AND_OUT,
    'Blue fading in and out': PresetEffect.BLUE_FADING_IN_AND_OUT,
    'Yellow fading in and out': PresetEffect.YELLOW_FADING_IN_AND_OUT,
    'Cyan fading in and out': PresetEffect.CYAN_FADING_IN_AND_OUT,
    'Purple fading in and out': PresetEffect.PURPLE_FADING_IN_AND_OUT,
    'White fading in and out': PresetEffect.WHITE_FADING_IN_AND_OUT,
    'Red meteor reverse': PresetEffect.RED_METEOR_REVERSE,
    'Green meteor reverse': PresetEffect.GREEN_METEOR_REVERSE,
    'Blue meteor reverse': PresetEffect.BLUE_METEOR_REVERSE,
    'Yellow meteor reverse': PresetEffect.YELLOW_METEOR_REVERSE,
    'Cyan meteor reverse': PresetEffect.CYAN_METEOR_REVERSE,
    'Purple meteor reverse': PresetEffect.PURPLE_METEOR_REVERSE,
    'White meteor reverse': PresetEffect.WHITE_METEOR_REVERSE,
    'Red wave 2': PresetEffect.RED_WAVE_2,
    'Green wave 2': PresetEffect.GREEN_WAVE_2,
    'Blue wave 2': PresetEffect.BLUE_WAVE_2,
    'Yellow wave 2': PresetEffect.YELLOW_WAVE_2,
    'Cyan wave 2': PresetEffect.CYAN_WAVE_2,
    'Purple wave 2': PresetEffect.PURPLE_WAVE_2,
    'White wave 2': PresetEffect.WHITE_WAVE_2,
    'Red wing dots': PresetEffect.RED_WING_DOTS,
    'Green swing dots': PresetEffect.GREEN_SWING_DOTS,
    'Blue swing dots': PresetEffect.BLUE_SWING_DOTS,
    'Yellow swing dots': PresetEffect.YELLOW_SWING_DOTS,
    'Cyan swing dots': PresetEffect.CYAN_SWING_DOTS,
    'Purple swing dots': PresetEffect.PURPLE_SWING_DOTS,
    'White swing dots': PresetEffect.WHITE_SWING_DOTS,
    'Red and green cudgel': PresetEffect.RED_AND_GREEN_CUDGEL,
    'Green and blue cudgel': PresetEffect.GREEN_AND_BLUE_CUDGEL,
    'Blue and yellow cudgel': PresetEffect.BLUE_AND_YELLOW_CUDGEL,
    'Yellow and cyan cudgel': PresetEffect.YELLOW_AND_CYAN_CUDGEL,
    'Cyan and purple cudgel': PresetEffect.CYAN_AND_PURPLE_CUDGEL,
    'Purple and white cudgel': PresetEffect.PURPLE_AND_WHITE_CUDGEL,
    'White and red cudgel': PresetEffect.WHITE_AND_RED_CUDGEL,
    'Red overlaps green': PresetEffect.RED_OVERLAPS_GREEN,
    'Green overlaps red': PresetEffect.GREEN_OVERLAPS_RED,
    'Blue overlaps green': PresetEffect.BLUE_OVERLAPS_GREEN,
    'Yellow overlaps green': PresetEffect.YELLOW_OVERLAPS_GREEN,
    'Cyan overlaps green': PresetEffect.CYAN_OVERLAPS_GREEN,
    'Purple overlaps green': PresetEffect.PURPLE_OVERLAPS_GREEN,
    'White overlaps green': PresetEffect.WHITE_OVERLAPS_GREEN,
    'Red overlaps blue': PresetEffect.RED_OVERLAPS_BLUE,
    'Green overlaps blue': PresetEffect.GREEN_OVERLAPS_BLUE,
    'Blue overlaps green 2': PresetEffect.BLUE_OVERLAPS_GREEN_2,
    'Yellow overlaps blue': PresetEffect.YELLOW_OVERLAPS_BLUE,
    'Cyan overlaps blue': PresetEffect.CYAN_OVERLAPS_BLUE,
    'Purple overlaps blue': PresetEffect.PURPLE_OVERLAPS_BLUE,
    'White overlaps blue': PresetEffect.WHITE_OVERLAPS_BLUE,
    'Pink mix blue': PresetEffect.PINK_MIX_BLUE,
    'Green mix yellow': PresetEffect.GREEN_MIX_YELLOW,
    'Blue mix pink': PresetEffect.BLUE_MIX_PINK,
    'Blue mix white': PresetEffect.BLUE_MIX_WHITE,
    'Green mix orange': PresetEffect.GREEN_MIX_ORANGE,
    'Blue mix purple': PresetEffect.BLUE_MIX_PURPLE,
    'Cyan mix white': PresetEffect.CYAN_MIX_WHITE,
    'Red blinking': PresetEffect.RED_BLINKING,
    'Green blinking': PresetEffect.GREEN_BLINKING,
    'Blue blinking': PresetEffect.BLUE_BLINKING,
    'Yellow blinking': PresetEffect.YELLOW_BLINKING,
    'Cyan blinking': PresetEffect.CYAN_BLINKING,
    'Purple blinking': PresetEffect.PURPLE_BLINKING,
    'White blinking': PresetEffect.WHITE_BLINKING,
    'Red stacking into green': PresetEffect.RED_STACKING_INTO_GREEN,
    'Green stacking into blue': PresetEffect.GREEN_STACKING_INTO_BLUE,
    'Blue stacking into yellow': PresetEffect.BLUE_STACKING_INTO_YELLOW,
    'Yellow stacking into cyan': PresetEffect.YELLOW_STACKING_INTO_CYAN,
    'Cyan stacking into purple': PresetEffect.CYAN_STACKING_INTO_PURPLE,
    'Purple stacking into white': PresetEffect.PURPLE_STACKING_INTO_WHITE,
    'White stacking into red': PresetEffect.WHITE_STACKING_INTO_RED,
    'Color changing breathing': PresetEffect.COLOR_CHANGING_BREATHING,
    'Multicolored gradients': PresetEffect.MULTICOLORED_GRADIENTS,
    'Color Flashing': PresetEffect.COLOR_FLASHING,
    'Rainbow reverse': PresetEffect.RAINBOW_REVERSE
}

CUSTOM_EFFECTS = {
    'Custom Effect 1': CustomEffect.CUSTOM_1,
    'Custom Effect 2': CustomEffect.CUSTOM_2,
    'Custom Effect 3': CustomEffect.CUSTOM_3,
    'Custom Effect 4': CustomEffect.CUSTOM_4,
    'Custom Effect 5': CustomEffect.CUSTOM_5,
    'Custom Effect 6': CustomEffect.CUSTOM_6,
    'Custom Effect 7': CustomEffect.CUSTOM_7,
    'Custom Effect 8': CustomEffect.CUSTOM_8,
    'Custom Effect 9': CustomEffect.CUSTOM_9,
    'Custom Effect 10': CustomEffect.CUSTOM_10,
    'Custom Effect 11': CustomEffect.CUSTOM_11,
    'Custom Effect 12': CustomEffect.CUSTOM_12,
}

